config/routes.rb
Rails.application.routes.draw do
  resources :artworks
  resources :artists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
end

app/models/artwork.rb
class Artwork < ApplicationRecord
  has_one_attached :file

  belongs_to :artist, optional: true

  validates :artist, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[ show edit update destroy ]

  # GET /artists
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  def create
    @artist = Artist.new(artist_params)

    if @artist.save
      redirect_to @artist, notice: "Artist was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /artists/1
  def update
    if @artist.update(artist_params)
      redirect_to @artist, notice: "Artist was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /artists/1
  def destroy
    @artist.destroy!
    redirect_to artists_path, notice: "Artist was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def artist_params
      params.fetch(:artist, {})
    end
end

app/controllers/artworks_controller.rb
class ArtworksController < ApplicationController
  before_action :set_artwork, only: %i[ show edit update destroy ]

  # GET /artworks
  def index
    @artworks = Artwork.all
  end

  # GET /artworks/1
  def show
  end

  # GET /artworks/new
  def new
    @artwork = Artwork.new
  end

  # GET /artworks/1/edit
  def edit
  end

  # POST /artworks
  def create
    @artwork = Artwork.new(artwork_params)

    if @artwork.save
      redirect_to @artwork, notice: "Artwork was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /artworks/1
  def update
    if @artwork.update(artwork_params)
      redirect_to @artwork, notice: "Artwork was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /artworks/1
  def destroy
    @artwork.destroy!
    redirect_to artworks_path, notice: "Artwork was successfully destroyed.", status: :see_other
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artwork
      @artwork = Artwork.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def artwork_params
      params.fetch(:artwork, {}).permit(:artist_id, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/artworks_helper.rb
module ArtworksHelper
end

app/views/artists/_artist.html.erb
<div id="<%= dom_id artist %>">
</div>

app/views/artists/_form.html.erb
<%= form_with(model: artist) do |form| %>
  <% if artist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
        <% artist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<% content_for :title, "Editing artist" %>

<h1>Editing artist</h1>

<%= render "form", artist: @artist %>

<br>

<div>
  <%= link_to "Show this artist", @artist %> |
  <%= link_to "Back to artists", artists_path %>
</div>

app/views/artists/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Artists" %>

<h1>Artists</h1>

<div id="artists">
  <% @artists.each do |artist| %>
    <%= render artist %>
    <p>
      <%= link_to "Show this artist", artist %>
    </p>
  <% end %>
</div>

<%= link_to "New artist", new_artist_path %>

app/views/artists/new.html.erb
<% content_for :title, "New artist" %>

<h1>New artist</h1>

<%= render "form", artist: @artist %>

<br>

<div>
  <%= link_to "Back to artists", artists_path %>
</div>

app/views/artists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artist %>

<div>
  <%= link_to "Edit this artist", edit_artist_path(@artist) %> |
  <%= link_to "Back to artists", artists_path %>

  <%= button_to "Destroy this artist", @artist, method: :delete %>
</div>

app/views/artworks/_artwork.html.erb
<div id="<%= dom_id artwork %>">
</div>

app/views/artworks/_form.html.erb
<%= form_with(model: artwork) do |form| %>
  <% if artwork.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(artwork.errors.count, "error") %> prohibited this artwork from being saved:</h2>

      <ul>
        <% artwork.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :artist_id %>
    <%= form.text_field :artist_id, value: Artist.first&.id %>
  </div>

  <div>
    <%= form.label :file, style: "display: block" %>
    <%= form.file_field :file %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/artworks/edit.html.erb
<% content_for :title, "Editing artwork" %>

<h1>Editing artwork</h1>

<%= render "form", artwork: @artwork %>

<br>

<div>
  <%= link_to "Show this artwork", @artwork %> |
  <%= link_to "Back to artworks", artworks_path %>
</div>

app/views/artworks/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Artworks" %>

<h1>Artworks</h1>

<div id="artworks">
  <% @artworks.each do |artwork| %>
    <%= render artwork %>
    <p>
      <%= link_to "Show this artwork", artwork %>
    </p>
  <% end %>
</div>

<%= link_to "New artwork", new_artwork_path %>

app/views/artworks/new.html.erb
<% content_for :title, "New artwork" %>

<h1>New artwork</h1>

<%= render "form", artwork: @artwork %>

<br>

<div>
  <%= link_to "Back to artworks", artworks_path %>
</div>

app/views/artworks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artwork %>

<div>
  <%= link_to "Edit this artwork", edit_artwork_path(@artwork) %> |
  <%= link_to "Back to artworks", artworks_path %>

  <%= button_to "Destroy this artwork", @artwork, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Active Storage Bug Demo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>